const TableActionTypes = {
    SET_BASIC_INCREMENT: 'SET_BASIC_INCREMENT',
    SET_ADVANCED_INCREMENT: 'SET_ADVANCED_INCREMENT',
    SET_PREMIUM_INCREMENT: 'SET_PREMIUM_INCREMENT',
    SET_PREMIUM_TWO_INCREMENT: 'SET_PREMIUM_TWO_INCREMENT',
    SET_LUXURY_INCREMENT: 'SET_LUXURY_INCREMENT',
    SET_LUXURY_TWO_INCREMENT: 'SET_LUXURY_TWO_INCREMENT',
    SET_BASIC_DECREMENT: 'SET_BASIC_DECREMENT',
    SET_ADVANCED_DECREMENT: 'SET_ADVANCED_DECREMENT',
    SET_PREMIUM_DECREMENT: 'SET_PREMIUM_DECREMENT',
    SET_PREMIUM_TWO_DECREMENT: 'SET_PREMIUM_TWO_DECREMENT',
    SET_LUXURY_DECREMENT: 'SET_LUXURY_DECREMENT',
    SET_LUXURY_TWO_DECREMENT: 'SET_LUXURY_TWO_DECREMENT',
}

export default TableActionTypes;